pre_install() {
  /bin/true
}

## arg 1:  the new package version
post_install() {
  ln -s /usr/lib/xword/xword /usr/bin/xword
}

## arg 1:  the new package version
## arg 2:  the old package version
pre_upgrade() {
  /bin/true
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  /bin/true
}

## arg 1:  the old package version
pre_remove() {
  /bin/true
}

## arg 1:  the old package version
post_remove() {
  rm /usr/bin/xword
}

# vim:set ts=2 sw=2 et:
