post_install() {
  getent group lock >/dev/null || groupadd -g 54 lock
  getent group utmp >/dev/null || groupadd -g 22 utmp

  echo "systemd has been installed to /bin/systemd. Please ensure you append"
  echo "init=/bin/systemd to your kernel command line in your bootloader."
}

post_upgrade() {
  echo ":: Call \`systemctl daemon-reexec' to reload systemd"
}

post_remove() {
  getent group lock && groupdel lock
  getent group utmp && groupdel utmp
} /dev/null

# vim:set ts=2 sw=2 et:
